services:
  init:
    image: debian:stable-slim
    command: chown -v 1000:1000 /moved_attachments
    volumes:
      - ./moved_attachments:/moved_attachments
  bot:
#    image: signal-cli
    build:
      context: docker/signal-cli
    user: "1000:1000"
    env_file: .env
    mem_limit: 250m
    volumes:
      - /home/lars/.local/share/signal-cli:/home/user/.local/share/signal-cli
      - ./:/output
  attachment-mover:
    depends_on:
      - init
    #    image: attachment-mover-java
    build:
      context: .
      dockerfile: docker/attachment-mover-java/Dockerfile
    #    entrypoint: bash -c 'echo "up"; while(true); do sleep 1; done'
    user: "1000:1000"
    mem_limit: 90m
    volumes:
      - /home/lars/.local/share/signal-cli/attachments:/signal_attachments
      - ./moved_attachments:/moved_attachments
      - ./:/output:ro
