name: Docker CI

on: [ push ]

jobs:
  build:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Docker Setup Docker
        # You may pin to the exact commit or the version.
        # uses: docker/setup-docker-action@370a7dad4b8ce8dbf00f9363e1652e5074dd6abe
        uses: docker/setup-docker-action@v4.1.0
        #with:
        # Docker CE version. (e.g, v24.0.9)
        # version: # optional, default is latest
        # Docker CE channel. (e.g, stable, edge or test)
        # channel: # optional
        # Docker daemon JSON configuration
        # daemon-config: # optional
        # TCP port to expose the Docker API locally
        # tcp-port: # optional
        # Docker context name. (default setup-docker-action)
        #context: # optional
        # Set DOCKER_HOST environment variable to docker socket path
        # set-host: # optional, default is false
        # Enable Docker rootless mode
        # rootless: # optional, default is false
      - name: Build and Test run.sh
        run: ./run.sh